---
crackin:
  name: crackin
  debug: true
  scm: git
  changelog: CHANGELOG.md
  branch:
    production: master
    development: develop
  status:
    verbose: false
  version: lib/crackin/version.rb
  build:
    command: rake build
    after: []
